services:
  app:
    build: .
    container_name: milktea-secured
    restart: always
    environment:
      - PORT=3000
      - NODE_ENV=production
      - SESSION_SECRET=${SESSION_SECRET:-}
    volumes:
      - secured-data:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.milktea-secured.rule=Host(`secured-milktea.zoskisk.com`)"
      - "traefik.http.routers.milktea-secured.entrypoints=websecure"
      - "traefik.http.services.milktea-secured.loadbalancer.server.port=3000"
      - "traefik.http.routers.milktea-secured.tls.certresolver=letsencrypt"
    networks:
      - traefik_default

volumes:
  secured-data:

networks:
  traefik_default:
    external: true
